#!/usr/bin/env bash

cf_networks() {
	echo "# From $1"
	printf 'set_real_ip_from %s;\n' $(curl -sS "$1" | sort)
	echo ""
}

cf_conf() {
	echo "# CloudFlare"
	echo ""
	cf_networks https://www.cloudflare.com/ips-v4
	cf_networks https://www.cloudflare.com/ips-v6
	echo "real_ip_header X-Forwarded-For;"
	echo "real_ip_recursive on;"
	echo ""
}

# Generate cloudflare.conf from CloudFlare's public network lists
cf_conf >tpl/etc/nginx/cloudflare.conf
