#!/bin/bash

IMAGE_NAME=${IMAGE_NAME-dirtsimple/php-server:${DOCKER_TAG%%,*}}

case $DOCKER_TAG in
	7.1.*|7.2.26|7.3.13)
		PHP_VER=${DOCKER_TAG%%-*}; OS_VER=3.9;;
	7.*)
		PHP_VER=${DOCKER_TAG%%-*}; OS_VER=3.10;;
esac

docker build ${PHP_VER+ --build-arg PHP_VER=$PHP_VER}${OS_VER+ --build-arg OS_VER=$OS_VER} -f "${DOCKERFILE_PATH-Dockerfile}" -t "$IMAGE_NAME" .

for tag in ${DOCKER_TAG//,/ }; do
	echo "Tagging ${IMAGE_NAME%%:*}:$tag"
	[[ $tag == "${IMAGE_NAME/##*:}" ]] || docker tag "$IMAGE_NAME" "${IMAGE_NAME%%:*}:$tag"
done