#!/bin/bash

# Run specified command as developer user
if (($#)); then printf -v cmd " %q" "$@"; cmd="${cmd# }"; else cmd=""; fi

set -e

if [[ $(whoami) == 'developer' ]]; then
    # Already the user, just do it
    exec /bin/bash -c "$cmd"
else
    export HOME=~developer
    export PATH=$CODE_BASE/vendor/bin:$HOME/.wp-cli/packages/vendor/bin:$COMPOSER_HOME/vendor/bin:$PATH
    exec su -p developer -s /bin/bash -c "$cmd"
fi
