#!/bin/bash

# Run specified command as nginx user
cmd=$@

if [[ $(whoami) == 'nginx' ]]; then
    exec /bin/bash -c "$cmd"
else
    export HOME=/var/cache/nginx
    exec su -p nginx -s /bin/bash -c "$cmd"
fi
