#!/usr/bin/env bash
export COMPOSER_ALLOW_SUPERUSER=1
mkdir -p /composer
cd /composer

args=()

if-composer() {
	local prog; printf -v prog "$@"
	[[ -f composer.json ]] && jq -e "$prog" composer.json >/dev/null
}

have() {
	if [[ $1 == *:* ]]; then
		if-composer '.require."%s" == "%s"' "${1%%:*}" "${1#*:}"
	else
		if-composer '.require|has("%s")' "${1%%:*}"
	fi
}

minstab() { if-composer '."minimum-stability" == "%s"' "$1"; }


for REPLY; do
	! have "$REPLY" || continue
	echo "need $REPLY"
	if [[ $REPLY = *:dev* ]] && ! minstab dev; then
		echo "Setting minimum-stability = dev"
		composer global config minimum-stability dev
	fi
    case $REPLY in
        hirak/prestissimo|hirak/prestissimo:*)
            echo "Installing prestissimo first, to accelerate other installs"
            composer global require --prefer-dist "$REPLY"
            ;;
        *)  args+=("$REPLY") ;;
    esac
done

if ((${#args[@]})); then composer global require --prefer-dist "${args[@]}"; fi
