#!/bin/bash
set -e

uninstalled_apks() {
    grep -vxF -f <(apk info | sort) <(for apk; do echo $apk; done)
    true
}

uninstalled_exts() {
    local exts=($(php -m)) ext_base="/usr/local/etc/php/conf.d/docker-php-ext-"
    shopt -s nocaseglob
    for ext; do [[ " ${exts[*]} " == *"$ext"* || -f "${ext_base}${ext%:*}.ini" ]] || echo $ext; done
}

install_pecls() {
    docker-php-source extract
    apk add --virtual .phpize-deps $PHPIZE_DEPS
    for pecl; do
        pecl install "${pecl/:/-}"
        docker-php-ext-enable "${pecl/%:*}"
    done
    apk del .phpize-deps
    docker-php-source delete
}

apks=$(    uninstalled_apks tzdata $EXTRA_APKS)
installs=$(uninstalled_exts $EXTRA_EXTS)
pecls=$(   uninstalled_exts $EXTRA_PECL)

if [[ "$apks"     ]]; then apk add $apks; fi
if [[ "$installs" ]]; then install-php-extensions $installs; fi
if [[ "$pecls"    ]]; then install_pecls $pecls; fi

