#!/bin/bash

if [ ! -f /etc/letsencrypt/live/$DOMAIN/privkey.pem ] ; then
    mode=setup
else
    mode=renew
fi

GIT_EMAIL="$LETS_ENCRYPT" WEBROOT="${WEBROOT-/var/www/html}" /usr/bin/letsencrypt-$mode

