#!/bin/bash

main() {
    install-extras || exit 1
    setup-environment-vars
    setup-nginx-user
    generate-system-configuration

    if ! checkout-exists; then
        perform-git-checkout
    fi

    apply-nginx-permissions
    generate-user-configuration

    if composer.json-exists; then
        run-composer-install
    fi

    run-user-scripts
    exec-supervisord
}


checkout-exists()      { [ -d "$CODE_BASE/.git" ]; }
composer.json-exists() { [ -f "$CODE_BASE/composer.json" ]; }
glob-list()            ( shopt -s nullglob; echo $1; )

setup-environment-vars() {
    # Set up CODE_BASE, PUBLIC_DIR, and WEBROOT

    CODE_BASE=${CODE_BASE:-/var/www/html}
    export CODE_BASE="$(realpath $CODE_BASE)" || exit 1  # must exist!

    cd "$CODE_BASE"

    export PUBLIC_DIR="$(realpath ${PUBLIC_DIR-.})" || exit 1 # must exist!
    export WEBROOT="${WEBROOT-${PUBLIC_DIR}}"
}


generate-system-configuration() {
    expand-templates /tpl /

    # Git config
    [[ -z "$GIT_NAME" ]]  || git config --system user.name  "$GIT_NAME";
    [[ -z "$GIT_EMAIL" ]] || git config --system user.email "$GIT_EMAIL";
    git config --system push.default simple
}

ensure-dir() {
    [[ -d "$1" ]] || mkdir -p "$1" || exit 1
}

expand-template() {
    # Expand precisely one template file to a target filename
    reject-nginx-writable "$1"
    ensure-dir "$(dirname "$2")"
    dockerize -template "$1:$2" || exit 1
}

reject-nginx-writable() {
    dv=($(stat -Lc "%U %G %A" "$1")) && (
        [[ "${dv[0]}" == "nginx" ]] || [[ "${dv[2]:8:1}" == "w" ]] ||
        ( [[ "${dv[2]:5:1}" == "w" ]] && [[ "${NGINX_GROUPS[*]}" =~ ^(.* |)${dv[1]}( .*|)$ ]] )
    ) && echo >&2 "${2-Template} file $1 must not be writable by nginx" && exit 1
}

expand-templates() {
    # Setup configuration files based on environment
    local src="$1" dst="${2-/}"
    cd "$CODE_BASE"     # process everything relative to CODE_BASE
    if [[ -d "$src" ]]; then
        # Source directory exists: expand subtree under destination dir
        ensure-dir "$dst"
        src="$(realpath "$src")" dst="$(realpath "$dst")"
        for f in $(find "$src" -type f); do
            expand-template "$f" "${dst%/}${f#$src}"
        done
    fi
}

setup-nginx-user() {
    # Re-create nginx user w/specified UID/GID
    if [ ! -z "$PUID" ]; then
        if [ -z "$PGID" ]; then PGID=${PUID}; fi
        deluser nginx
        addgroup -g ${PGID} nginx
        adduser -D -S -h /var/cache/nginx -s /sbin/nologin -G nginx -u ${PUID} nginx
    fi
    NGINX_GROUPS=($(groups nginx))
}

grant-nginx() { [[ -z "$3" ]] || ( ch$1 -Rf nginx $3 && chmod -Rf $2 $3 ) || exit 1 ; }

apply-nginx-permissions() { grant-nginx grp g+r "${NGINX_READABLE-.}" && grant-nginx grp g+w "$NGINX_WRITABLE" ; }

perform-git-checkout() {
    # Pull down code from git for our site!
    if [ ! -z "$GIT_REPO" ]; then
        # Remove the test index file if you are pulling in a git repo
        if ! isTrue "${REMOVE_FILES-true}"; then
            echo "skipping removal of files"
        else
            rm -Rf $CODE_BASE/*
        fi
        GIT_COMMAND='git clone '
        if [ ! -z "$GIT_BRANCH" ]; then
            GIT_COMMAND=${GIT_COMMAND}" -b ${GIT_BRANCH}"
        fi
        if [ -z "$GIT_USERNAME" ] && [ -z "$GIT_PERSONAL_TOKEN" ]; then
            GIT_COMMAND=${GIT_COMMAND}" ${GIT_REPO}"
        else
            if isTrue "$GIT_USE_SSH"; then
                GIT_COMMAND=${GIT_COMMAND}" ${GIT_REPO}"
            else
                GIT_COMMAND=${GIT_COMMAND}" https://${GIT_USERNAME}:${GIT_PERSONAL_TOKEN}@${GIT_REPO}"
            fi
        fi
        as-nginx ${GIT_COMMAND} || exit 1
    fi
}

generate-user-configuration() {
    # Enable custom nginx config files if they exist
    for tag in "" "-ssl"; do
        if [ -f $CODE_BASE/conf/nginx/nginx-site$tag.conf ]; then
            cp $CODE_BASE/conf/nginx/nginx-site$tag.conf  /etc/nginx/sites-available/default$tag.conf
        fi
    done

    # Install env-templated files if they exist - paths are relative to $CODE_BASE
    for tpl in ${DOCKERIZE_TEMPLATES}; do
        # deliberately leaving off quotes here to split on `:`
        expand-templates ${tpl/:/ }
    done
}


run-composer-install() {
    # Try auto install for composer
    as-nginx composer install --no-dev --working-dir=$CODE_BASE || exit 1
}

run-user-scripts() {
    if isTrue "$RUN_SCRIPTS"; then
        RUN_SCRIPTS="$CODE_BASE/scripts";
    fi
    if [[ ! -z "$RUN_SCRIPTS" ]] && [[ -d "$RUN_SCRIPTS" ]]; then
        # run scripts in number order
        for i in $(glob-list "$RUN_SCRIPTS/*"); do
            reject-nginx-writable "$i"
            chmod ug+x "$i" && "$i" || exit 1
        done
    fi
}

exec-supervisord() {
    # Start supervisord and services
    exec /usr/bin/supervisord -n -c /etc/supervisord.conf
}

main

