name: Update project description on Docker Hub

on:
  push:
    branches: [ "master" ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Trim README
        run: |
          sed -i -e 's~(#~(https://github.com/dirtsimple/php-server/#~; /tocstop/,/^#\+ Version Info/{/^#\+ Version Info/!d}' README.md

      - name: Update repo description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ github.repository }}
